version: '3.8'

services:
  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=faculdade_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=senha_segura
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: faculdade_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_segura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
